### ISSUE TITLE
Full vs negsamp-based evaluation on WikiKGv2?

### ISSUE THREAD

**Issue by apoorvumang** [migalkin/NodePiece#3]
Hi

Congratulations on the ICLR acceptance!

I noticed in the paper that on the link prediction task, performance of NodePiece is significantly better compared to strong baselines (eg. ComplEx) on WikiKGv2 despite being consistently worse on other datasets (fb15k-237, wn18rr, yago, codex). Do you think this is due to WikiKGv2 being a large dataset, or some other reason?

As you know, unlike other datasets, wikikgv2 uses negative sampling while evaluating (1 true answer needs to be ranked correctly among 500 random negatives). IMO this is incorrect and unnecessary, since it makes the task much easier - for eg. ogb's own wikikg90m changed from negative sampling based evaluation to full evaluation (rank among all entities) in the v2 of their dataset due to suspiciously high performance of several methods.

My question is - have you tried full evaluation (ie rank all 2.5M entities) of NodePiece on wikikgv2? Does NodePiece still beat ComplEx when evaluating on the full setting, or is it just on the much easier negsamp-based evaluation?

Also, do you have plans on trying NodePiece on other large KGs such as WikiData5M, WikiKG90Mv2 etc.?

Thanks

**Comment by migalkin** [comment]
Hi, thanks!

We took the WikiKG2 as one of the established benchmarks with all its pros (size) and cons (evaluation protocol). We might question some design choices of this dataset but it is what it is - at least all the benchmarked models on the leaderboard follow the same evaluation protocol and the results are comparable.

> have you tried full evaluation (ie rank all 2.5M entities) of NodePiece on wikikgv2?

No, as there is no official established benchmark for that, and fine-tuning hyperparams of baseline models like complex or rotate was not part of our study (and would take a ton on compute).

> Also, do you have plans on trying NodePiece on other large KGs such as WikiData5M, WikiKG90Mv2 etc.?

Yes, Wikidata5M and WikiKG90M v2 have a better evaluation protocol, although it is more of an engineering task to scale the tokenization process, ie, anchor mining, to such large graphs. You would need some partitioning algorithm like METIS to split the graph to N chunks equal to the number of compute nodes at hand, and run the process in parallel (or apply other large-scale graph processing tricks). 

Besides, you would also need to "chunkify" the ranking procedure, eg storing a matrix of 90M 100d float32 vectors (to score **one** triple against all candidate entities) would already require 36 GB of memory. Instead, you'd want to compute, say, batches of 100k columns at a time and update the scores matrix. 

Something that will work right now out of the box: we recently integrated NodePiece into [PyKEEN](https://github.com/pykeen/pykeen) (here is the [doc](https://pykeen.readthedocs.io/en/latest/api/pykeen.models.NodePiece.html)) and Wikidata5M is already there, so you can experiment with the the memory-inexpensive RelationTokenizer (w/o anchors) and train some models, although I don't have an estimate how good or bad would it be.

**Comment by apoorvumang** [comment]
Thank you so much for the informative answer!

Yes WikiKG90Mv2 would be a big task and require some engineering to run on small memory GPUs. WikiData5M would be an interesting experiment. I might try to run it with PyKEEN and see how it runs, will let you know whatever results I get. Thanks for making NodePiece part of a KGE library 👍
