### ISSUE TITLE
TypeError: evaluate() got an unexpected keyword argument 'additional_filter_triples'

### ISSUE THREAD

**Issue by huang0926huang** [migalkin/NodePiece#4]
Hi,

Thanks for the great work. I was trying to run the inductive_lp experiment on RTX3090. Because of the hashrate mismatch, I can't install pytorch=1.7.1 on the RTX3090. So I directly chose to configure the corresponding environment with cuda11.6.

```
Traceback (most recent call last):
  File "/home/ps/hh/NodePiece-main/inductive_lp/run_ilp.py", line 236, in <module>
    main()
  File "/home/ps/miniconda3/envs/nodepiece/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ps/miniconda3/envs/nodepiece/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ps/miniconda3/envs/nodepiece/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ps/miniconda3/envs/nodepiece/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ps/hh/NodePiece-main/inductive_lp/run_ilp.py", line 215, in main
    metric_results = test_evaluator.evaluate(
TypeError: evaluate() got an unexpected keyword argument 'additional_filter_triples'
```

Below you may find a list of package versions in my environment.
```
python         3.8.13
pykeen                    1.0.5
python-igraph             0.10.1
click                     8.1.3
einops                    0.5.0
numpy                     1.23.3
torch                     1.12.1+cu116            
torch-cluster             1.6.0                   
torch-geometric           2.1.0.post1         
torch-scatter             2.0.9                 
torch-sparse              0.6.15              
torch-spline-conv         1.2.1              
tqdm                      4.64.1               
```
Please correct me if I am wrong. Would be good if you could give me some advice.If it is a very basic and simple mistake, allow me to apologize for taking up your precious time.Thank you.

**Comment by migalkin** [comment]
Hi, not sure why you needed particular `pykeen==1.7.1`, but you can already use inductive link prediction with NodePiece with the latest version of pykeen (1.9.0), the datasets are integrated there as well

**Comment by huang0926huang** [comment]
Thank you for your help. Upgrading the version of the ```pykeen``` package does solve the problem of TypeError.At the same time, ImportError will also appear, but that's what I should do next. Apologize again for taking up your precious time.
